### ISSUE TITLE
Scrollbar visible

### ISSUE THREAD

**Issue by babarogic** [CodyHouse/cd-off-canvas-navigation-changelog#1]
https://www.loom.com/share/1a01d09fa14d4b848572c6d705385215

**Comment by claudia-romano** [comment]
Hi there,
we fixed the issue with the scrollbar position:
https://codyhouse.co/ds/components/app/off-canvas-navigation

The scrollbar needs to be visible if the off-canvas navigation height is bigger than the viewport. This is not a bug but rather the expected behaviour (it allows you to access the entire navigation content).

Cheers
